workaround the error: 'hyperv_cs' undeclared
The full error is:

drivers/hv/hv_util.c: In function 'hv_get_adj_host_time':
drivers/hv/hv_util.c:225:12: error: 'hyperv_cs' undeclared (first use in this function)
  reftime = hyperv_cs->read(hyperv_cs);
            ^
drivers/hv/hv_util.c:225:12: note: each undeclared identifier is reported only once for each function it appears in
drivers/hv/hv_util.c: In function 'adj_guesttime':
drivers/hv/hv_util.c:264:16: error: 'hyperv_cs' undeclared (first use in this function)
  cur_reftime = hyperv_cs->read(hyperv_cs);
                ^
drivers/hv/hv_util.c: In function 'timesync_onchannelcallback':
drivers/hv/hv_util.c:329:12: error: 'hyperv_cs' undeclared (first use in this function)
            hyperv_cs->read(hyperv_cs),
            ^
drivers/hv/hv_util.c: In function 'hv_timesync_init':
drivers/hv/hv_util.c:535:7: error: 'hyperv_cs' undeclared (first use in this function)
  if (!hyperv_cs)
       ^
scripts/Makefile.build:269: recipe for target 'drivers/hv/hv_util.o' failed

BTW, we may need to backport this one, though it depends on channel)->callback_event:

HV: properly delay KVP packets when negotiation is in progress
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a3ade8cc474d848676278660e65f5af1e9e094d9

Signed-off-by: Dexuan Cui <decui@microsoft.com>