x86/hyperv: Fix undefined reference to isolation_type_en_snp without CONFIG_HYPERV
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2176350

commit 86e619c922e616d8780833562a14a5bda329f0c3
Author: Dexuan Cui <decui@microsoft.com>
Date:   Tue Aug 22 20:20:08 2023 -0700

    x86/hyperv: Fix undefined reference to isolation_type_en_snp without CONFIG_HYPERV

    When CONFIG_HYPERV is not set, arch/x86/hyperv/ivm.c is not built (see
    arch/x86/Kbuild), so 'isolation_type_en_snp' in the ivm.c is not defined,
    and this failure happens:

    ld: arch/x86/kernel/cpu/mshyperv.o: in function `ms_hyperv_init_platform':
    arch/x86/kernel/cpu/mshyperv.c:417: undefined reference to `isolation_type_en_snp'

    Fix the failure by testing hv_get_isolation_type() and
    ms_hyperv.paravisor_present for a fully enlightened SNP VM: when
    CONFIG_HYPERV is not set, hv_get_isolation_type() is defined as a
    static inline function that always returns HV_ISOLATION_TYPE_NONE
    (see include/asm-generic/mshyperv.h), so the compiler won't generate any
    code for the ms_hyperv.paravisor_present and static_branch_enable().

    Reported-by: Tom Lendacky <thomas.lendacky@amd.com>
    Closes: https://lore.kernel.org/lkml/b4979997-23b9-0c43-574e-e4a3506500ff@amd.com/
    Fixes: d6e2d6524437 ("x86/hyperv: Add sev-snp enlightened guest static key")
    Signed-off-by: Dexuan Cui <decui@microsoft.com>
    Signed-off-by: Wei Liu <wei.liu@kernel.org>
    Link: https://lore.kernel.org/r/20230823032008.18186-1-decui@microsoft.com

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>