x86/hyperv: declare hv_isolation_type_en_snp in asm-generic/mshyperv.h for ARM64
Add the declaration in asm-generic/mshyperv.h, otherwise the ARM64
build fails:

drivers/hv/hv.c: In function 'hv_synic_alloc':
drivers/hv/hv.c:128:7: error: implicit declaration of function 'hv_isolation_type_en_snp';

Fixes: 60b9b192d99a ("drivers: hv: Mark percpu hvcall input arg page unencrypted in SEV-SNP enlightened guest")
Signed-off-by: Dexuan Cui <decui@microsoft.com>